<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-VA0K6UF" failures="3" tests="11" name="Test" time="2.276" errors="0" timestamp="2022-08-14T15:09:26 IST">
  <testcase classname="training.testng.TestPriorization" name="createPatient" time="0.023"/>
  <testcase classname="training.testng.TestPriorization" name="updatePatient" time="0.003"/>
  <testcase classname="training.testng.AssertionExample" name="testone" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [Log off] but found [sign off]">
      <![CDATA[java.lang.AssertionError: expected [Log off] but found [sign off]
at training.testng.AssertionExample.testone(AssertionExample.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testone -->
  <testcase classname="training.testng.Annotations3" name="oneTest" time="0.003"/>
  <testcase classname="training.testng.Annotations2" name="threeTest" time="0.002"/>
  <testcase classname="training.testng.SoftAssertExample" name="softAssert" time="0.008">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [meet] but found [hp],
	expected [7878] but found [9898]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [meet] but found [hp],
expected [7878] but found [9898]
at training.testng.SoftAssertExample.softAssert(SoftAssertExample.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- softAssert -->
  <testcase classname="training.testng.SoftAssertExample" name="softAssert2" time="0.004"/>
  <testcase classname="training.testng.TestingExample" name="timeoutExample" time="2.026">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method training.testng.TestingExample.timeoutExample() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method training.testng.TestingExample.timeoutExample() didn't finish within the time-out 2000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- timeoutExample -->
  <testcase classname="training.testng.Annotations" name="firstTest" time="0.005"/>
  <testcase classname="training.testng.Annotations" name="secondTest" time="0.004"/>
  <testcase classname="training.testng.Annotations" name="thirdTest" time="0.003"/>
  <testcase classname="training.testng.Annotations2" name="twoTest" time="0.0">
    <ignored/>
  </testcase> <!-- twoTest -->
  <testcase classname="training.testng.TestPriorization" name="deletePatient" time="0.0">
    <ignored/>
  </testcase> <!-- deletePatient -->
  <testcase classname="training.testng.Annotations2" name="oneTest" time="0.0">
    <ignored/>
  </testcase> <!-- oneTest -->
</testsuite> <!-- Test -->
